# 键盘基本设置
CONFIG_ZMK_KEYBOARD_NAME="WHN1"
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# 启用OLED显示和I2C
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_I2C=y

# 关闭不需要的功能
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n